var nameList=[
    "Rex",
    "Levy",
    "Harlen",
    "James",
    "John",
    "Robert",
    "Michael",
    "William",
    "David",
    "Richard",
    "Charles",
    "Joseph",
    "Thomas",
    "Christopher",
    "Daniel",
    "Paul",
    "Mark",
    "Donald",
    "George",
    "Kenneth",
    "Steven",
    "Edward",
    "Brian",
    "Mary ",
    "Patricia",
    "Linda ",
    "Barbara ",
    "Elizabeth",
    "Jennifer",
    "Maria ",
    "Susan ",
    "Margaret",
    "Dorothy ",
    "Lisa ",
    "Nancy ",
    "Karen ",
    "Betty ",
    "Helen ",
    "Sandra ",
    "Donna ",
    "Carol ",
    "Ruth ",
    "Sharon ",
];
var prefixList=[
    "Aggressive",
    "Amazed",
    "Anxious",
    "Angry",
    "Bold",
    "Calm",
    "Brave",
    "Kind",
    "Ferocious",
    "Happy",
    "Exhausted",
    "Depressed",
    "Worrying",
    "Tactful",
    "Powerful",
    "Prideful",
    "Mysterious",
];

module.exports=function() {
    var name=nameList[Math.floor(Math.random()*nameList.length)];
    var pref=prefixList[Math.floor(Math.random()*prefixList.length)];
    return pref+" "+name;
}
